services:
  - type: web
    name: checklist-travel
    runtime: python
    buildCommand: "pip install -r requirements.txt && python generate_destinations_json.py"
    startCommand: "gunicorn app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10